# Generated by Django 3.1.2 on 2020-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
