"""
Django settings for assessment project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ROOT_DIR = (
    environ.Path(__file__) - 3
)

PROJECT_DIR = (
    environ.Path(__file__) - 2
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v!!_2mu@80uh-i&h&*_o+19-=ula#exujy@m8%)ejm__&j%n59'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_framework_swagger',

    # local apps
    'apps.users',
    'apps.assess'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'users.User'

ROOT_URLCONF = 'assessment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assessment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# 'default': {
#     'ENGINE': 'django.db.backends.sqlite3',
#     'NAME': BASE_DIR / 'db.sqlite3',
# },

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'assessment_db2',
        'USER': 'assessmentuser',
        'PASSWORD': 'assessmentpass',
        'HOST': 'localhost',
        'PORT': ''
    }
}
DATABASES["default"]["ATOMIC_REQUESTS"] = True

# db = 'assessment_db'
# user = 'assessmentuser'
# pass = 'assessmentpass'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# ---------------- REST_FRAMEWORK settings ----------------
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'PAGE_SIZE': 1,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'ORDERING_PARAM': 'ordering',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}
# ---------------- REST_FRAMEWORK settings ----------------

CORS_ALLOW_ALL_ORIGINS = True


# -----------------_Email settings --------------------
# SMTP username: Your Gmail address
# SMTP password: Your Gmail password
# SMTP server address: smtp.gmail.com
# Gmail SMTP port (TLS): 587
# SMTP port (SSL): 465
# SMTP TLS/SSL required: yes

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sat.info8117@gmail.com'
EMAIL_HOST_PASSWORD = '8117@satinfo'
EMAIL_PORT = 587
FROM_EMAIL = 'sat.info8117@gmail.com'

# --------------------twitter credentials-------------------
consumer_key = "ik26TghbAz0NLMMHv8bvbTwgV"
consumer_secret = "bmdlMg9bqvjrSnq8KRHt1OPG6WgiqstMlzW45TBPRFFsTYtqSw"
access_key = "1303743972959907840-GQpz6HbrkAr5BVm2Fqdeh0EM0IyxGS"
access_secret = "XyqV7uK11wsl9IGXaxYCQC5oS3LqlegZzZgGCjdmUvlyh"

# ------------------watson credentials---------------
tone_api_key = '6E6_UbW83z2oCIcFZPKL0-r0LLcq661o1k53YlP8XQxK'
tone_url = 'https://api.eu-gb.tone-analyzer.watson.cloud.ibm.com/instances/3106f266-1599-4254-861b-2926f42c3bed'

nlu_api_key = 'MIEe405f57MQ7yiMQxb04lTi6M8wofjfnP1Lpv3qn4eG'
nlu_url = 'https://api.eu-gb.natural-language-understanding.watson.cloud.ibm.com/instances/a7eec1f1-f31e-4553-88b1-37810d814e55'
